export const details = {
    pl: 'portfolio',
    homeAbout: {
        tit: 'Heyy!',
        desc: `I'm Shailesh Tiwari, A web developer focused on building beautiful websites`,
        butt: 'MORE ABOUT ME',
    },
    homeblog: {
        title: 'Keep Scrolling',
        desc: 'To find out more :)',
    },
    homePort: {
        desc: 'Some of my latest projects',
        butt: 'See all projects',
    },
    menu: {
        footer: 'Made by Shailesh Tiwari with ❤️',
        text: 'Want to work with me?',
        menuList: {
            ho: 'Home',
            ab: 'About me',
            po: 'Portfolio',
            co: 'Contact',
        },
        contDesc: {
            desc: 'If you want to communicate with me or are interested in starting a project together, get in touch.',
            em: 'Send me an email :)',
            so: 'Or send me a direct message on my social media.',
        },
    },
    about: {
        h1: 'Hi! I am',
        h2: 'Shailesh Tiwari',
        p1: 'Web Developer',
        abh1: 'About me',
        abp1: 'Hi! I am Shailesh Tiwari. I have a great passion for design and technology. I specialize in Frontend development although I also have a background in Backend and my passion is building elegant and professional websites and user interfaces.',
        abp2: 'My first steps in development and programming were in college where I learned the basics of C ++, after that I discovered web development, which gave me and hooked me, so I decided to focus on it and forge a career in frontend developer. It was for this reason that I made the decision to learn everything related to web development in a self-taught way and thus be able to build professional and interactive websites.',
        abp3: 'Although my goal is to become a full Frontend developer, I will not be left alone with it. My goal is to take it to the next level and become a Full Stack developer. It was for this reason that I decided to join Henry where I learned technologies and work methodologies that would allow me to meet my goals.',
        abp4: 'I prepare myself daily to meet the challenges in this ever-changing world and will do my best to meet my goals.',
        skh1: 'My Skills',
        skp1: 'For development / coding, I use different tools specific to application or website development. The tools and technologies that I use and are familiar with are listed below.',
        skh41: 'Software / tools',
        skh42: 'Web development',
        mhh3: '“Choose a job you love and you will never have to work a day in your life.”',
        bt: 'See my work',
    },
    portfolio: {
        t1: 'My projects',
        t2: 'Note',
        ap1: 'My portfolio consists of project websites and a react native game app. In each one I put tried putting the maximum effort, attention and creativity.',
        ap2: 'These are some of the projects that I have worked on. You can also find the code of each project on my',
        cards: [
            {
                title: 'Covid Vaccine Tracker',
                img: 'https://res.cloudinary.com/dsgtwehup/image/upload/v1635761259/covid_tracker_um5rom.png',
                imgMobile:
                    'https://res.cloudinary.com/dsgtwehup/image/upload/v1635761259/covid_tracker_um5rom.png',
                descTitle: 'Project Description',
                desc: 'A basic website that shows the current vaccination status in india and was built purely to test how many featues I could add in such a single project',
                liTitle1: 'Platform',
                liDesc1: 'Web/Mobile',
                liTitle2: 'Category',
                liDesc2: 'Heathcare',
                liTitle3: 'Developer',
                liDesc3: 'Shailesh Tiwari',
                techT: 'Technologies Used',
                techP: 'HTML<span>/</span>CSS<span>/</span>JavaScript<span>/</span>Chartjs<span>',
                butDemo: 'Launch App',
                butRepo: 'Source Code',
                linkDemo: 'https://github.com/shlesh',
                linkRepo: 'https://github.com/shlesh',
            },
            {
                title: 'SC0R3K33P3R',
                img: 'https://res.cloudinary.com/dsgtwehup/image/upload/v1635761763/5c0r3k33p3r_wtjqcw.png',
                imgMobile:
                    'https://res.cloudinary.com/dsgtwehup/image/upload/v1635761763/5c0r3k33p3r_wtjqcw.png',
                descTitle: 'Project Description',
                desc: 'A live scoreleeper that relies on the SportsMonk API to fetch data and display the webpage accordingly.',
                liTitle1: 'Platform',
                liDesc1: 'Web/Mobile',
                liTitle2: 'Category',
                liDesc2: 'Utility',
                liTitle3: 'Developer',
                liDesc3: 'Shailesh Tiwari',
                techT: 'Technologies Used',
                techP: 'HTML<span>/</span>CSS<span>/</span>JavaScript<span>/</span>React<span>/</span>SportsMonk API',
                butDemo: 'Launch App',
                butRepo: 'Source Code',
                linkDemo: 'hhttps://github.com/shlesh',
                linkRepo: 'https://github.com/shlesh',
            },
            {
                title: 'Personal Portfolio',
                img: 'https://res.cloudinary.com/dsgtwehup/image/upload/v1635770142/Portfolio_site_zcvv0s.png',
                imgMobile:
                    'https://res.cloudinary.com/dsgtwehup/image/upload/v1635770142/Portfolio_site_zcvv0s.png',
                descTitle: 'Project Description',
                desc: 'Had always wanted to build a sweet personal porfolio site, and Opencode 2021 finally gave me the motivation and the oppurtunity to get working on one. Many of the ideas used in this project have been taken Codepen and Codesandbox resources, but it turned out to be a great learning curve as I finally got a chance to work with redux and in the process came out with one of the most worthwhile and memorable projects Ive attempted.',
                liTitle1: 'Platform',
                liDesc1: 'Web/Mobile',
                liTitle2: 'Category',
                liDesc2: 'Productivity',
                liTitle3: 'Developer',
                liDesc3: 'Shailesh Tiwari',
                techT: 'Technologies Used',
                techP: 'HTML<span>/</span>CSS<span>/</span>JavaScript<span>/</span>React<span>/</span>Styled-Components<span>/</span>EmailJS',
                butDemo: 'Launch App',
                butRepo: 'Source Code',
                linkDemo: 'https://github.com/shlesh',
                linkRepo: 'https://github.com/shlesh',
            },
        ],
    },
    contact: {
        title: 'Get in touch.',
        desc: 'en',
        fname: 'Your name',
        femail: 'Your email',
        fsubject: 'Subject',
        ftext: 'YOUR MESSAGE',
        fbutton: 'Send Message',
    },
};
