const og = repo => `https://opengraph.githubassets.com/1/shlesh/${repo}`;

const project = ({
    title,
    repo,
    desc,
    platform = 'Web',
    category,
    tech,
    demo,
    demoLabel = 'Launch App',
}) => ({
    title,
    img: og(repo),
    imgMobile: og(repo),
    descTitle: 'Project Description',
    desc,
    liTitle1: 'Platform',
    liDesc1: platform,
    liTitle2: 'Category',
    liDesc2: category,
    liTitle3: 'Developer',
    liDesc3: 'Shailesh Tiwari',
    techT: 'Technologies Used',
    techP: tech,
    butDemo: demoLabel,
    butRepo: 'Source Code',
    linkDemo: demo || `https://github.com/shlesh/${repo}`,
    linkRepo: `https://github.com/shlesh/${repo}`,
});

export const details = {
    pl: 'portfolio',
    homeAbout: {
        titl: 'Heyy!',
        desc: `I'm Shailesh Tiwari, A web developer focused on building beautiful websites`,
        btn: 'MORE ABOUT ME',
    },
    homescroll: {
        title: 'Keep Scrolling',
        desc: 'To find out more :)',
    },
    homePort: {
        desc: 'Some of my latest projects',
        btn: 'See all projects',
    },
    menu: {
        footer: 'Made by Shailesh Tiwari with ❤️',
        text: 'Want to work with me?',
        menuList: {
            ho: 'Home',
            ab: 'About me',
            po: 'Portfolio',
            co: 'Contact',
        },
        contDesc: {
            desc: 'If you want to contact me or are interested in starting a project together, get in touch.',
            em: 'Send me an email :)',
            so: 'Or send me a direct message on my social media.',
        },
    },
    about: {
        h1: 'Hi! I am',
        h2: 'Shailesh Tiwari',
        p1: 'Web Developer',
        abh1: 'About me',
        abp1: 'Hi! I am Shailesh Tiwari. I have a great passion for design and technology. I specialize in Frontend development although I also have a background in Backend and my passion is building elegant and professional websites and user interfaces.',
        abp2: 'My first steps in development and programming were in college where I learned the basics of C ++, after that I discovered web development, which got me hooked, so I decided to focus on it and forge a career as a frontend developer. It was for this reason that I made the decision to learn everything related to web development in a self-taught way and thus be able to build professional and interactive websites.',
        abp3: 'Although my goal is to become a full Frontend developer, I will not be left alone with it. My goal is to take it to the next level and become a Full Stack developer. It was for this reason that I decided to start learning backend after opencode started and have even gotten a chance to try my hand at it.',
        abp4: 'I prepare myself daily to meet the challenges in this ever-changing world and will do my best to meet my goals.',
        skh1: 'My Skills',
        skp1: 'For development / coding, I use different tools specific to application or website development. The tools and technologies that I use and are familiar with are listed below.',
        skh41: 'Software / tools',
        skh42: 'Web development',
        mhh3: '“Choose a job you love and you will never have to work a day in your life.”',
        bt: 'My Work',
    },
    portfolio: {
        t1: 'My projects',
        t2: 'Note',
        ap1: 'These are projects I have shipped across the web, astrology, writing tools, games and experiments. Each one got real attention and care.',
        ap2: 'You can also find the code for each project on my',
        cards: [
            project({
                title: 'Cosmic Dharma',
                repo: 'CosmicDharma',
                desc: 'A Vedic astrology app with a Next.js frontend and FastAPI backend. Generates birth profiles, dashas and house analysis, plus a Markdown blog, donor reports and an admin dashboard. Built as a PWA and live at cosmicdharma.app.',
                platform: 'Web / PWA',
                category: 'Astrology',
                tech: 'Next.js<span>/</span>React<span>/</span>FastAPI<span>/</span>Python<span>/</span>Redis<span>/</span>Postgres',
                demo: 'https://cosmicdharma.app',
            }),
            project({
                title: 'Moon+ Theme Maker',
                repo: 'moonreader-theme-maker',
                desc: 'A small web app to design Moon+ Reader themes in the browser, preview them live and download a .mrthemes file ready to import into the app.',
                platform: 'Web',
                category: 'Utility',
                tech: 'HTML<span>/</span>CSS<span>/</span>JavaScript',
                demo: 'https://shlesh.github.io/moonreader-theme-maker/',
            }),
            project({
                title: 'kriya-llm',
                repo: 'kriya-llm',
                desc: 'A training library for fine-tuning Qwen 2.5 on Kriya Yoga source texts so the model can speak from that lineage instead of generic chat data.',
                platform: 'Library',
                category: 'Machine Learning',
                tech: 'Python<span>/</span>Qwen 2.5<span>/</span>PyTorch',
                demoLabel: 'View Repo',
            }),
            project({
                title: 'Project WOL',
                repo: 'project-wol',
                desc: 'A web writing studio for drafting, exporting and eventually publishing longer work. Built for people who want a quiet place to write and take the manuscript with them.',
                platform: 'Web',
                category: 'Productivity',
                tech: 'JavaScript<span>/</span>Web',
                demoLabel: 'View Repo',
            }),
            project({
                title: 'DOMS',
                repo: 'DOMS',
                desc: 'A rebuild of the Department of Management Studies site on a Gatsby storefront theme, with custom pages, layout and content structure.',
                platform: 'Web',
                category: 'Website',
                tech: 'Gatsby<span>/</span>React<span>/</span>CSS Modules',
                demoLabel: 'View Repo',
            }),
            project({
                title: 'Emotional Intelligence Event',
                repo: 'newEvent',
                desc: 'Landing page for an Emotional Intelligence event organized at IIITA. Clean static page with event details and structure.',
                platform: 'Web',
                category: 'Event',
                tech: 'HTML<span>/</span>CSS',
                demoLabel: 'View Repo',
            }),
            project({
                title: 'GDSC Email Template',
                repo: 'GDSC-Email-Template',
                desc: 'Reusable HTML email template for GDSC communications so club mail stays consistent across campaigns.',
                platform: 'Email',
                category: 'Design',
                tech: 'HTML<span>/</span>CSS',
                demoLabel: 'View Repo',
            }),
            project({
                title: 'Flappy Block',
                repo: 'Flappy-Block',
                desc: 'A browser Flappy Bird-style game built as a quick HTML experiment around timing, collision and scoring.',
                platform: 'Web',
                category: 'Game',
                tech: 'HTML<span>/</span>CSS<span>/</span>JavaScript',
                demoLabel: 'View Repo',
            }),
            project({
                title: 'Todo App',
                repo: 'todo-app',
                desc: 'A straightforward React todo list for adding, completing and clearing tasks. Built while getting comfortable with component state.',
                platform: 'Web',
                category: 'Productivity',
                tech: 'React<span>/</span>JavaScript<span>/</span>CSS',
                demoLabel: 'View Repo',
            }),
            project({
                title: 'Project Gravity',
                repo: 'ProjectGravity',
                desc: 'An early CodeSandbox experiment that grew into the Gravity Innovations work. A playground for layout and interaction ideas.',
                platform: 'Web',
                category: 'Experiment',
                tech: 'JavaScript<span>/</span>React',
                demoLabel: 'View Repo',
            }),
            project({
                title: 'Guess My Number',
                repo: 'GuessMyNumber-Game',
                desc: 'A small guessing game where you try to land on a secret number. Early CSS and JavaScript practice with feedback and score.',
                platform: 'Web',
                category: 'Game',
                tech: 'HTML<span>/</span>CSS<span>/</span>JavaScript',
                demoLabel: 'View Repo',
            }),
            project({
                title: 'Dice Game',
                repo: 'DiceGame',
                desc: 'A two-player dice game in the browser. Roll, hold and race to the target score.',
                platform: 'Web',
                category: 'Game',
                tech: 'HTML<span>/</span>CSS<span>/</span>JavaScript',
                demoLabel: 'View Repo',
            }),
            {
                title: 'Covid Vaccine Tracker',
                img: 'https://res.cloudinary.com/dsgtwehup/image/upload/v1635761259/covid_tracker_um5rom.png',
                imgMobile:
                    'https://res.cloudinary.com/dsgtwehup/image/upload/v1635761259/covid_tracker_um5rom.png',
                descTitle: 'Project Description',
                desc: 'A basic website that shows the current vaccination status in india and was built purely to test how many featues I could add in a single project',
                liTitle1: 'Platform',
                liDesc1: 'Web/Mobile',
                liTitle2: 'Category',
                liDesc2: 'Heathcare',
                liTitle3: 'Developer',
                liDesc3: 'Shailesh Tiwari',
                techT: 'Technologies Used',
                techP: 'HTML<span>/</span>CSS<span>/</span>JavaScript<span>/</span>Chartjs<span>',
                butDemo: 'Launch App',
                butRepo: 'Source Code',
                linkDemo: 'https://github.com/shlesh',
                linkRepo: 'https://github.com/shlesh',
            },
            {
                title: 'SC0R3K33P3R',
                img: 'https://res.cloudinary.com/dsgtwehup/image/upload/v1635761763/5c0r3k33p3r_wtjqcw.png',
                imgMobile:
                    'https://res.cloudinary.com/dsgtwehup/image/upload/v1635761763/5c0r3k33p3r_wtjqcw.png',
                descTitle: 'Project Description',
                desc: 'A live scorekeeper that relies on the SportsMonk API to fetch data and display the webpage accordingly.',
                liTitle1: 'Platform',
                liDesc1: 'Web/Mobile',
                liTitle2: 'Category',
                liDesc2: 'Utility',
                liTitle3: 'Developer',
                liDesc3: 'Shailesh Tiwari',
                techT: 'Technologies Used',
                techP: 'HTML<span>/</span>CSS<span>/</span>JavaScript<span>/</span>React<span>/</span>SportsMonk API',
                butDemo: 'Launch App',
                butRepo: 'Source Code',
                linkDemo: 'https://github.com/shlesh',
                linkRepo: 'https://github.com/shlesh',
            },
            {
                title: 'Personal Portfolio',
                img: 'https://res.cloudinary.com/dsgtwehup/image/upload/v1635770142/Portfolio_site_zcvv0s.png',
                imgMobile:
                    'https://res.cloudinary.com/dsgtwehup/image/upload/v1635770142/Portfolio_site_zcvv0s.png',
                descTitle: 'Project Description',
                desc: 'Had always wanted to build a sweet personal porfolio site, and Opencode 2021 finally gave me the motivation and the oppurtunity to get working on one. Many of the ideas used in this project have been taken Codepen and Codesandbox resources, but it turned out to be a great learning curve as I finally got a chance to work with redux and in the process came out with one of the most worthwhile and memorable projects Ive attempted.',
                liTitle1: 'Platform',
                liDesc1: 'Web/Mobile',
                liTitle2: 'Category',
                liDesc2: 'Productivity',
                liTitle3: 'Developer',
                liDesc3: 'Shailesh Tiwari',
                techT: 'Technologies Used',
                techP: 'HTML<span>/</span>CSS<span>/</span>JavaScript<span>/</span>React<span>/</span>Styled-Components<span>/</span>EmailJS',
                butDemo: 'Launch App',
                butRepo: 'Source Code',
                linkDemo: 'https://github.com/shlesh/portfolio-site',
                linkRepo: 'https://github.com/shlesh/portfolio-site',
            },
        ],
    },
    contact: {
        title: 'Get in touch.',
        fname: 'Your name',
        femail: 'Your email',
        fsubject: 'Subject',
        ftext: 'YOUR MESSAGE',
        fbutton: 'Send Message',
    },
};
